# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# Status: 
# - verified action triggered by the new release.
# - correct upload to with test.pypi
# - correct installation from test.pypi.org: pip install --index-url https://test.pypi.org/simple/ publish-test

name: Upload Python Package

on:
  [push]
#  release:
#    types: [created]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]

        
    steps:
      - uses: actions/checkout@v3

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install pip packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install setuptools wheel twine

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel==2.7.0

      - name: Build wheels
        run: python3 -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        #env:
        #  CIBW_BEFORE_BUILD: pip install pybind11

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl    
      
      
      - name: PYPI publish
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_JBREZ_USER }}
          TWINE_PASSWORD: ${{ secrets.PYPI_JBREZ_PASS }}
        run: |
          #python setup.py sdist bdist_wheel
          twine upload dist/*
          # twine upload --repository-url https://test.pypi.org/legacy/ dist/*
         
        
